### ISSUE TITLE
Creality v4.2.7 

### ISSUE THREAD

**Issue by Emile58-F** [Flawioo/Creality-Ender-3-board-v4.2.7#1]
Hello. Excuse me, this is the right connection, to install a bl touch. Because here I bought from the Amazon.fr site but the hookups with 5 pins is the same creality v4.2.7 motherboard you can help me please ... Good night Emile58-F

**Comment by Flawioo** [comment]
> Hello. Excuse me, this is the right connection, to install a bl touch. Because here I bought from the Amazon.fr site but the hookups with 5 pins is the same creality v4.2.7 motherboard you can help me please ... Good night Emile58-F

Hi @Emile58-F sure I'll try to help you. Please can you get some pictures and share here with me? I'm not sure if i got your problem...

**Comment by Emile58-F** [comment]
Good evening. the bltouch model is not the same i don't see the color code, i place the photos you requested. I think I was wrong I took for a cr-10 instead of ender 3d, yet I saw which was compatible.


M. Emile Fautres
![20200829_233105~2](https://user-images.githubusercontent.com/70258616/91647279-5b1f7a80-ea59-11ea-94e4-1c235e7a522f.jpg)
![20200829_234050~2](https://user-images.githubusercontent.com/70258616/91647280-5c50a780-ea59-11ea-8307-342a33ab26a8.jpg)

**Comment by Flawioo** [comment]
> Good evening. the bltouch model is not the same i don't see the color code, i place the photos you requested. I think I was wrong I took for a cr-10 instead of ender 3d, yet I saw which was compatible.
> 
> M. Emile Fautres
> ![20200829_233105~2](https://user-images.githubusercontent.com/70258616/91647279-5b1f7a80-ea59-11ea-94e4-1c235e7a522f.jpg)
> ![20200829_234050~2](https://user-images.githubusercontent.com/70258616/91647280-5c50a780-ea59-11ea-8307-342a33ab26a8.jpg)

Hi, Try this:
![image](https://user-images.githubusercontent.com/17605608/91648967-9b283280-ea44-11ea-87ad-7b098ed1b074.png)

It supposed you may have to change the wire order to get it working.
First of all check servo (blue, red and yellow) and only after make them work ok lets to next step that is the probe itself (black and white).

**Comment by Flawioo** [comment]
No feedback, I think the question iwas solved.
