### ISSUE TITLE
Z Homing with BLTouch

### ISSUE THREAD

**Issue by TzOk83** [Flawioo/Creality-Ender-3-board-v4.2.7#12]
When I configured BLTouch on a dedicated port (PB1) and commented out #define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN, I couldn't find a way to set Z-Offset. My solution was to uncomment #define USE_PROBE_FOR_Z_HOMING to ignore the existence of the Z End-Stop. After finding the right value, I could revert to use Z End-Stop for homing, and also disable Z_SAFE_HOMING, as it is not needed when using Z End-Stop for homing.

**Comment by Flawioo** [comment]
Hi! 

> When I configured BLTouch on a dedicated port (PB1) and commented out #define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN, I couldn't find a way to set Z-Offset. My solution was to uncomment #define USE_PROBE_FOR_Z_HOMING to ignore the existence of the Z End-Stop. After finding the right value, I could revert to use Z End-Stop for homing, and also disable Z_SAFE_HOMING, as it is not needed when using Z End-Stop for homing.

Hi! 
Thank you for your worth information, there are many parameter combinations and get the right as you've tried is awesome.
