### ISSUE TITLE
Incorrect default_envs for v4.2.7 Creality Silent Mainboard

### ISSUE THREAD

**Issue by The-300lb-Gorilla** [Flawioo/Creality-Ender-3-board-v4.2.7#15]
In platformio.ini
Change: default_envs = mega2560
To: default_envs = STM32F103RET6_creality <----Outdated (2 Years Old)  Will not compile using this default_envs.

In platformio.ini
Change: default_envs = mega2560
To: default_envs = STM32F103RE_creality <------ Corrected as of November 28 2022. Will compile using this default_envs.
                                                                                Tested and Confirmed on November 28 2022

**Comment by Flawioo** [comment]
Corrected by @TechSupportE2Pro .

Thanks!

**Comment by The-300lb-Gorilla** [comment]
Your Welcome
