### ISSUE TITLE
Gros Probleme

### ISSUE THREAD

**Issue by b3nym4n0o** [Flawioo/Creality-Ender-3-board-v4.2.7#5]
I have an Ender 3, upgrade silent motherboard v1.1.5 (4.2.7) 32 bit with TMC2225 adding a BLTOUCH V1 and an end of filament detector, I'm in direct drive with a MICROSWISS kit I have flash the firmware with MARLIN 2.0 (find tutorial on youtube and on Github) * it doesn't work * 

the lcd menu has to be changed, can't configure the Z-OFFSET, Axis control manually; little not lower the value under the '' 0 '' so after a ''AUTO HOME'', I find myself with my nozzle at about 125mm in height, my bl touch is useless.

**Comment by Flawioo** [comment]
Hi @b3nym4n0o 
Please compile again but you have to comment the line with MIN_SOFTWARE_ENDSTOP_Z to allow to set Z offset in negative values.

Change: #define MIN_SOFTWARE_ENDSTOP_Z
To: //#define MIN_SOFTWARE_ENDSTOP_Z // To allow to set Z offset values in negative

And check if the bltouch is connected as follows:
![image](https://user-images.githubusercontent.com/17605608/94047074-f5988280-fda7-11ea-88a3-e0642a35b2ac.png)
