### ISSUE TITLE
Just to make sure

### ISSUE THREAD

**Issue by zevv** [Flawioo/Creality-Ender-3-board-v4.2.7#9]
Hey,

I recently upgraded my board to the v4.2.7 for reasons of noise reduction, but I lost my M600

Just to make sure: firmware-20200903-164823-Simplest+FilChange-m600-enabled.bin is basically similar, configuration-wise, to the stock Creality v0.0.6, but with M600 enabled?

Thanks!

**Comment by Flawioo** [comment]
> stock Creality v0.0.6

Hi! Sorry I can't confirm it to you because I've never used stock firmware from creality because them never have worked to me.

**Comment by zevv** [comment]
Aah right. Well, I tried yours on my Ender3, but the endstop inputs seem to mismatch the firmware, so homing is broken to start with.

Thanks anyway!

**Comment by Flawioo** [comment]
> Aah right. Well, I tried yours on my Ender3, but the endstop inputs seem to mismatch the firmware, so homing is broken to start with.

Ohh, seriously? Nobody have said it to me before. If I got a new info like that I'll make a troubleshooting to get that. You are welcome.

**Comment by zevv** [comment]
It might just be me, I have no clue how this board is or is not suppost to work with what printer. I have a stock Ender 3, but upgraded the board to the v4.2.7 which comes with creality "0.0.6". That works all fine as expected, the only thing it lacks is support for M600.

I can Gcode my way around it for now, but if I ever learn more about what's the issue I'll let you know.

**Comment by Flawioo** [comment]
I'll  really appreciate, thank you. Good prints!
